docker_builder:
  name: flutter:$DOCKER_TAG
  env:
    # from https://flutter.dev/docs/development/tools/sdk/releases
    matrix:
      - DOCKER_TAG: latest
        FLUTTER_VERSION: 3.19.5
      - DOCKER_TAG: stable
        FLUTTER_VERSION: 3.19.5
      - DOCKER_TAG: beta
        FLUTTER_VERSION: 3.21.0-0.0.pre
  version_script: docker --version
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  ci_script: ./ci.sh
