task:
  name: flutter:$DOCKER_TAG
  compute_engine_instance:
    image_project: khulnasoft-images
    image: family/docker-kvm
    platform: linux
    cpu: 4
    memory: 16G
  env:
    # from https://flutter.dev/docs/development/tools/sdk/releases
    matrix:
      - DOCKER_TAG: latest
        FLUTTER_VERSION: 3.19.5
      - DOCKER_TAG: stable
        FLUTTER_VERSION: 3.19.5
      - DOCKER_TAG: beta
        FLUTTER_VERSION: 3.22.0-0.1.pre
  version_script: docker --version
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  build_script: ./build_docker.sh
  push_script: ./push_docker.sh
docker_builder:
  env:
    matrix: []
